#!/usr/bin/env bash

PORT='5000'

# PORT CHECKING
echo exit | nc localhost $PORT

if [ $? -eq 0 ]; then
    echo "something is already running on $PORT"
    exit 1
fi

# https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
set -e 

OUTPUT='./dist'
BUNDLE='./public/bundle'

rm -rf $OUTPUT
rm -rf $BUNDLE

./node_modules/.bin/webpack --config ./webpack/prod.config.js

PORT=$PORT node server & 
SERVER_PID=$!

set +e

# wait for the server to start up
while ! echo exit | nc 0.0.0.0 $PORT; do sleep 1; done

./script/generator.js "http://0.0.0.0:$PORT" $OUTPUT

GEN_EXIT=$?

kill $SERVER_PID

set -e

if [ $GEN_EXIT -eq 0 ]; then
    cp -R public/* $OUTPUT
else
    exit $GEN_EXIT
fi
